version: '3'

services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    env_file: ./.env
    ports:
      - "8080:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
